version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=quest_db
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
    driver: local 

    

