version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db_quest
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=quest_db
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


    

